[package]
name = "manga-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.14"
scraper = "0.14"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
sanitize-filename = "0.2"
structopt = "0.3"